print('test.lua:1: assertion failed!')
